name: Package and deploy to NuGet

on:
  release:
    types: [ published ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Package BlazorReports
        run: dotnet pack src/BlazorReports

      - name: Package BlazorReports.Components
        run: dotnet pack src/BlazorReports.Components

      - name: Upload packages to NuGet
        run: dotnet nuget push 'artifacts/package/release/*.nupkg' --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
